version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/src
      # - .env.test.docker:/src/.env.test
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: ./.env.dev.docker
    environment:
      DATASETTE_URL: https://datasette.digital-land.info
      DATA_FILE_URL: https://data.digital-land.info
    healthcheck:
      test: curl -v -i -f http://localhost:8000
      interval: 1s
      timeout: 3s
      retries: 60

  db:
    image: postgis/postgis:13-master
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${DB_HOST_PORT-5432:}5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digital_land
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    name: digital-land
