version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      WRITE_DATABASE_URL: "postgresql://postgres:postgres@db/digital_land"
      READ_DATABASE_URL: "postgresql://postgres:postgres@db/digital_land"
      PRE_START_PATH: /src/prestart-dev.sh
      PORT: 8000
      RELOAD: "true"
      WEB_CONCURRENCY: 1

  db:
    image: postgis/postgis:13-master
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digital_land

volumes:
  postgres_data:
