version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/src
      - .env.test.docker:/src/.env.test
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      WRITE_DATABASE_URL: "postgresql://postgres:postgres@db/digital_land"
      READ_DATABASE_URL: "postgresql://postgres:postgres@db/digital_land"
      PRE_START_PATH: /src/prestart-dev.sh
      PORT: 8000
      RELOAD: "true"
      WEB_CONCURRENCY: 1
      S3_HOISTED_BUCKET: ${S3_HOISTED_BUCKET}
      S3_COLLECTION_BUCKET: ${S3_COLLECTION_BUCKET}

  db:
    image: postgis/postgis:13-master
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${DB_HOST_PORT-5432:}5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digital_land
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
