apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digital-land-platform-postgis-data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
