"""drop fact table

Revision ID: 53f6b9454d36
Revises: 41b96ad0a4e2
Create Date: 2022-06-01 11:18:21.448633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "53f6b9454d36"
down_revision = "41b96ad0a4e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_fact_entity", table_name="fact")
    op.drop_table("fact")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fact",
        sa.Column("fact", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("entity", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("field", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("reference_entity", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("entry_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("fact", name="fact_pkey"),
    )
    op.create_index("idx_fact_entity", "fact", ["entity"], unique=False)
    # ### end Alembic commands ###
