"""correct indexes for entity fields and drop fact

Revision ID: 543a95beb74b
Revises: 41b96ad0a4e2
Create Date: 2022-06-29 17:57:39.303711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "543a95beb74b"
down_revision = "41b96ad0a4e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index("idx_fact_entity", table_name="fact", info={"ifexists": True})
    op.drop_table("fact")
    op.execute(
        "DROP INDEX IF EXISTS entity__new_entity_name_entry_date_start_date_end_date_data_idx;",
    )
    op.create_index("idx_entity_dataset", "entity", ["dataset"], unique=False)
    op.create_index("idx_entity_end_date", "entity", ["end_date"], unique=False)
    op.create_index("idx_entity_entry_date", "entity", ["entry_date"], unique=False)
    op.create_index("idx_entity_name", "entity", ["name"], unique=False)
    op.create_index(
        "idx_entity_organisation_entity",
        "entity",
        ["organisation_entity"],
        unique=False,
    )
    op.create_index("idx_entity_prefix", "entity", ["prefix"], unique=False)
    op.create_index("idx_entity_reference", "entity", ["reference"], unique=False)
    op.create_index("idx_entity_start_date", "entity", ["start_date"], unique=False)
    op.create_index("idx_entity_typology", "entity", ["typology"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_entity_typology", table_name="entity")
    op.drop_index("idx_entity_start_date", table_name="entity")
    op.drop_index("idx_entity_reference", table_name="entity")
    op.drop_index("idx_entity_prefix", table_name="entity")
    op.drop_index("idx_entity_organisation_entity", table_name="entity")
    op.drop_index("idx_entity_name", table_name="entity")
    op.drop_index("idx_entity_entry_date", table_name="entity")
    op.drop_index("idx_entity_end_date", table_name="entity")
    op.drop_index("idx_entity_dataset", table_name="entity")

    op.create_index(
        "entity__new_entity_name_entry_date_start_date_end_date_data_idx",
        "entity",
        [
            "entity",
            "name",
            "entry_date",
            "start_date",
            "end_date",
            "dataset",
            "organisation_entity",
            "prefix",
            "reference",
            "typology",
        ],
        unique=False,
    )
    op.create_table(
        "fact",
        sa.Column("fact", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("entity", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("field", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("reference_entity", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("entry_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("fact", name="fact_pkey"),
    )
    op.create_index("idx_fact_entity", "fact", ["entity"], unique=False)
    # ### end Alembic commands ###
