"""add licence and attribution lookup tables for dataset

Revision ID: 6343e6290c55
Revises: 05283add2249
Create Date: 2022-08-09 17:20:00.576469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6343e6290c55"
down_revision = "05283add2249"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribution",
        sa.Column("attribution", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("attribution"),
    )
    op.create_table(
        "licence",
        sa.Column("licence", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("licence"),
    )
    op.alter_column("dataset", "attribution", new_column_name="attribution_id")
    op.alter_column("dataset", "licence", new_column_name="licence_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dataset", "attribution_id", new_column_name="attribution")
    op.alter_column("dataset", "licence_id", new_column_name="licence")

    op.drop_table("licence")
    op.drop_table("attribution")

    # ### end Alembic commands ###
