"""add quality_dimension to task

Revision ID: 695ba7321b7d
Revises: befd8e0ddca9
Create Date: 2026-09-10 10:54:39.964598

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "695ba7321b7d"
down_revision = "befd8e0ddca9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("quality_dimension", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "quality_dimension")
    # ### end Alembic commands ###
