"""add start_date to provision_quality

Revision ID: 9267492562be
Revises: 695ba7321b7d
Create Date: 2026-09-18 13:01:59.504709

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9267492562be"
down_revision = "695ba7321b7d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "provision_quality", sa.Column("start_date", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provision_quality", "start_date")
    # ### end Alembic commands ###
