"""add lookup table for entity references

Revision ID: 996863046410
Revises: 8c9f4367ff64
Create Date: 2022-05-17 12:44:40.001891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "996863046410"
down_revision = "8c9f4367ff64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lookup",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("entity", sa.BIGINT(), nullable=True),
        sa.Column("entry_number", sa.BIGINT(), nullable=True),
        sa.Column("prefix", sa.Text(), nullable=True),
        sa.Column("reference", sa.Text(), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lookup")
    # ### end Alembic commands ###
