"""add provision quality tables

Revision ID: befd8e0ddca9
Revises: 08139a9624a2
Create Date: 2026-07-20 12:24:16.305884

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "befd8e0ddca9"
down_revision = "08139a9624a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_quality",
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("authoritative_organisations", sa.Integer(), nullable=False),
        sa.Column("some_organisations", sa.Integer(), nullable=False),
        sa.Column("total_organisations", sa.Integer(), nullable=False),
        sa.Column("total_entities", sa.BIGINT(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("dataset"),
    )
    op.create_table(
        "organisation_quality",
        sa.Column("organisation", sa.Text(), nullable=False),
        sa.Column("organisation_name", sa.Text(), nullable=True),
        sa.Column("authoritative_datasets", sa.Integer(), nullable=False),
        sa.Column("some_datasets", sa.Integer(), nullable=False),
        sa.Column("total_datasets", sa.Integer(), nullable=False),
        sa.Column("total_entities_owned", sa.BIGINT(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("organisation"),
    )
    op.create_table(
        "provision_quality",
        sa.Column("dataset", sa.Text(), nullable=False),
        sa.Column("organisation", sa.Text(), nullable=False),
        sa.Column("organisation_name", sa.Text(), nullable=True),
        sa.Column("has_active_endpoint", sa.Boolean(), nullable=False),
        sa.Column("has_active_resource", sa.Boolean(), nullable=False),
        sa.Column("owns_entities", sa.Boolean(), nullable=False),
        sa.Column("is_designated_provider", sa.Boolean(), nullable=False),
        sa.Column("quality", sa.Text(), nullable=True),
        sa.Column("entity_count", sa.BIGINT(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("dataset", "organisation"),
    )
    op.create_index(
        "idx_provision_quality_organisation",
        "provision_quality",
        ["organisation"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_provision_quality_organisation", table_name="provision_quality")
    op.drop_table("provision_quality")
    op.drop_table("organisation_quality")
    op.drop_table("dataset_quality")
    # ### end Alembic commands ###
