"""Add quality column

Revision ID: fd4c9022a6c5
Revises: 3244f0ccb0dc
Create Date: 2025-11-14 22:27:57.555419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd4c9022a6c5"
down_revision = "3244f0ccb0dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entity", sa.Column("quality", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity", "quality")
    # ### end Alembic commands ###
