datasets_with_full_coverage:
  - agricultural-land-classification
  - air-quality-management-area
  - archaeological-priority-area
  - area-of-outstanding-natural-beauty
  - asset-of-community-value
  - battlefield
  - border
  - building-preservation-notice
  - built-up-area
  - central-activities-zone
  - certificate-of-immunity
  - educational-establishment
  - flood-risk-zone
  - flood-storage-area
  - green-belt
  - heritage-at-risk
  - heritage-coast
  - infrastructure-project
  - local-authority-district
  - local-nature-reserve
  - local-planning-authority
  - national-nature-reserve
  - national-park
  - nature-improvement-area
  - parish
  - park-and-garden
  - protected-wreck-site
  - ramsar
  - region
  - scheduled-monument
  - site-of-special-scientific-interest
  - special-area-of-conservation
  - special-protection-area
  - transport-access-node
  - ward
  - world-heritage-site
  - world-heritage-site-buffer-zone
