name: Continuous Integration
on:
  push:
  workflow_dispatch:

jobs:

  runner-job:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgis/postgis:13-master
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Make init
      run: |
        make init

    - name: Lint
      run: |
        make lint

    - name: Setup database
      run: |
        psql -h localhost -c "CREATE DATABASE digital_land_test WITH TEMPLATE postgres" -U postgres
      env:
        PGPASSWORD: postgres

    - name: Test
      run: |
        make test
        make test-acceptance
      env:
        DATASETTE_URL:  https://datasette.digital-land.info
        S3_COLLECTION_BUCKET: https://digital-land-production-collection-dataset.s3.eu-west-2.amazonaws.com
        S3_HOISTED_BUCKET: https://digital-land-production-collection-dataset-hoisted.s3.eu-west-2.amazonaws.com
        READ_DATABASE_URL: postgresql://postgres:postgres@localhost/digital_land_test
        WRITE_DATABASE_URL: postgresql://postgres:postgres@localhost/digital_land_test
        ENVIRONMENT: development

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      if: always() # always run even if the previous step fails
      with:
        report_paths: '.junitxml/*.xml'

    - name: Configure AWS credentials
      if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'  }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DL_WEB }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DL_WEB }}
        aws-region: eu-west-2

    - name: Login to ECR
      if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'  }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and tag as latest
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        IMAGE_TAG: latest
      run: |
        make EXPLICIT_TAG=$IMAGE_TAG docker-build

    - name: Build and tag as staging
      if: ${{ github.ref == 'refs/heads/staging' }}
      env:
        IMAGE_TAG: staging
      run: |
        make EXPLICIT_TAG=$IMAGE_TAG docker-build

    - name: Push to ECR as latest
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        IMAGE_TAG: latest
      run: |
        make EXPLICIT_TAG=$IMAGE_TAG push

    - name: Push to ECR as staging
      if: ${{ github.ref == 'refs/heads/staging' }}
      env:
        IMAGE_TAG: staging
      run: |
        make EXPLICIT_TAG=$IMAGE_TAG push

    - name: Restart digital-land.info service on production environment
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        ENVIRONMENT: production
      run: make ENVIRONMENT=$ENVIRONMENT deploy

    - name: Restart digital-land.info service on staging environment
      if: ${{ github.ref == 'refs/heads/staging' }}
      env:
        ENVIRONMENT: staging
        CF_USERNAME: ${{ secrets.GOV_PAAS_SERVICE_ACCOUNT_USERNAME }}
        CF_PASSWORD: ${{ secrets.GOV_PAAS_SERVICE_ACCOUNT_PASSWORD }}
      run: make ENVIRONMENT=$ENVIRONMENT deploy
