name: Publish & Deploy Smoke Test

on:
  push:
    branches: [main, feature/smoke-tests]
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The environment to deploy to.


jobs:
  detect-environments:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.environments.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: environments
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: json
          script: |
            if (context.payload?.inputs?.environment) return [context.payload?.inputs?.environment];
            const {data: {environments}} =
              await github.request(`GET /repos/${process.env.GITHUB_REPOSITORY}/environments`);
            return environments.map(e => e.name)

  publish-deploy:
    runs-on: ubuntu-latest
    needs: [detect-environments]
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.detect-environments.outputs.environments) }}
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install aws cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --update
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Prepare archive directory with correct file permissions
        working-directory: ./tests/smoke
        run: |
          sudo -s sh -c 'mkdir package'
          sudo -s sh -c 'chmod 0666 ./package'
          sudo -s sh -c 'mkdir package/python'
          sudo -s sh -c 'cp src/* ./package/python/.'

      - name: Create smoke test code archive
        working-directory: ./tests/smoke
        run: |
          sudo -s sh -c 'cd package && zip -r ../smoke-test-package.zip ./*'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

#      - name: Upload smoke test code archive to S3
#        working-directory: ./tests/smoke
#        run: |
#          aws s3 cp smoke-test-package.zip s3://${{ matrix.environment }}-canary-code-bucket/main/smoke-test-package.zip

#      - name: Get S3 Object version
#        id: canary-code-s3-version
#        run: |
#          S3_OBJECT_VERSION=$(aws s3api list-object-versions --bucket ${{ matrix.environment }}-canary-code-bucket --prefix main/smoke-test-package.zip --query 'Versions[?IsLatest].[VersionId]' --output text)
#          echo "VERSION=$S3_OBJECT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Update AWS Synthetics Canary function code in development environment
        if: ${{ matrix.environment == 'development' }}
        run: |
          aws synthetics update-canary \
              --name www \
              --code ZipFile=./tests/smoke/smoke-test-package.zip,Handler=smoke_canary.handler
#              --code S3Bucket=${{ matrix.environment }}-canary-code-bucket,S3Key=main/smoke-test-package.zip,S3Version=${{ steps.canary-code-s3-version.outputs.VERSION }},Handler=smoke_canary.handler
