name: Load Test

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL of the environment to test'
        required: true
        default: http://localhost:8000

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install locust==2.34.0

    - name: Run Locust load test
      run: |
        locust -f tests/load/website_test.py \
          -H ${{ github.event.inputs.target_url }} \
          --csv=log --html=locust_report.html \
          --headless -u 10 -r 1 -t 1m > locust_output.txt || true
          echo "### Locust Load Test Report" >> $GITHUB_STEP_SUMMARY
          echo "<a href='locust_report.html'>Click here to view the HTML report</a>" >> $GITHUB_STEP_SUMMARY


    - name: Upload Locust output
      uses: actions/upload-artifact@v4
      with:
        name: locust-results
        path: |
          locust_output.txt
          log_stats.csv
          log_failures.csv
          log_exceptions.csv
          log_stats_history.csv
