name: Load Test

on:
  # push:
  #   branches: load-test-automation
  workflow_dispatch:
    # inputs:
    #   target_url:
    #     description: 'URL of the environment to test'
    #     required: true
    #     default: https://www.staging.planning.data.gov.uk/

jobs:
  loadtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install locust==2.34.0

    - name: Run Locust load test
      run: |
        locust -f tests/load/website_test.py \
          -H http://localhost:8000 \
          --csv=log --html=locust_report.html \
          --headless -u 10 -r 1 -t 1m > locust_output.txt 2>&1 || true

    - name: Generate Locust markdown summary
      run: |
        echo "### Locust Load Test Summary" > locust_report.md
        echo "" >> locust_report.md
        echo "\`\`\`" >> locust_report.md
        cat locust_output.txt >> locust_report.md
        echo "\`\`\`" >> locust_report.md
        echo "" >> locust_report.md
        echo "Full HTML and CSV reports are uploaded as artifacts." >> locust_report.md

        cat locust_report.md >> $GITHUB_STEP_SUMMARY

    - name: Upload Locust output
      uses: actions/upload-artifact@v4
      with:
        name: locust-results
        path: |
          locust_output.txt
          locust_report.html
          log_stats.csv
          log_failures.csv
          log_exceptions.csv
          log_stats_history.csv
