name: Test
run-name: Test - ${{ github.head_ref || github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: make init
      - run: make lint

  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgis/postgis:14-master
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATASETTE_URL: https://datasette.digital-land.info
      DATA_FILE_URL: https://data.digital-land.info
      READ_DATABASE_URL: postgresql://postgres:postgres@localhost/digital_land_test
      WRITE_DATABASE_URL: postgresql://postgres:postgres@localhost/digital_land_test
      ENVIRONMENT: development
      PGPASSWORD: postgres
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - run: make init

      - name: Setup database
        run: |
          psql -h localhost -c "CREATE DATABASE digital_land_test WITH TEMPLATE postgres" -U postgres

      - name: Unit Tests
        run: |
          make test-unit
          echo "## Unit Tests" >> $GITHUB_STEP_SUMMARY
          cat unit-tests.md >> $GITHUB_STEP_SUMMARY

      - name: Integration Tests
        run: |
          make test-integration
          echo "## Integration Tests" >> $GITHUB_STEP_SUMMARY
          cat integration-tests.md >> $GITHUB_STEP_SUMMARY

      - name: Acceptance Tests
        run: |
          make test-acceptance
          echo "## Acceptance Tests" >> $GITHUB_STEP_SUMMARY
          cat acceptance-tests.md >> $GITHUB_STEP_SUMMARY

      - name: Accessibility Tests
        run: |
          make test-accessibility
          echo "## Accessibility Tests" >> $GITHUB_STEP_SUMMARY
          cat accessibility-tests.md >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
